language: objective-c
osx_image: xcode7.3

script:
  - |
    xcodebuild build \
    -project swift-lintcode.xcodeproj \
    -scheme swift-lintcode \
    -sdk iphonesimulator \
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'